# build environment
FROM node:10 as build
WORKDIR /usr/work_home

COPY package.json yarn.lock ./

RUN yarn --pure-lockfile

COPY . ./
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/work_home/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]