export const GET_BLOGS_REQUESTING = "GET_BLOGS_REQUESTING";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_ERROR = "GET_BLOGS_ERROR";

export const DELETE_BLOG_REQUESTING = "DELETE_BLOG_REQUESTING";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";