export const FILTER_ORGANIZATIONS_REQUESTING = "FILTER_ORGANIZATIONS_REQUESTING";
export const FILTER_ORGANIZATIONS_SUCCESS = "FILTER_ORGANIZATIONS_SUCCESS";
export const FILTER_ORGANIZATIONS_ERROR = "FILTER_ORGANIZATIONS_ERROR";