export const FILTER_QUESTIONS_REQUEST = "FILTER_QUESTIONS_REQUEST";
export const FILTER_QUESTIONS_REQUESTING = "FILTER_QUESTIONS_REQUESTING";
export const FILTER_QUESTIONS_SUCCESS = "FILTER_QUESTIONS_SUCCESS";
export const FILTER_QUESTIONS_ERROR = "FILTER_QUESTIONS_ERROR";

export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_REQUESTING = "CREATE_QUESTION_REQUESTING";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_ERROR = "CREATE_QUESTION_ERROR";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_REQUESTING = "UPDATE_QUESTION_REQUESTING";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_ERROR = "UPDATE_QUESTION_ERROR";

export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_REQUESTING = "GET_QUESTION_REQUESTING";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_ERROR = "GET_QUESTION_ERROR";