export const RESET_BLOG = "RESET_BLOG";
export const RESET_MESSAGE = "RESET_MESSAGE";

export const GET_BLOG_REQUESTING = "GET_BLOG_REQUESTING";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_ERROR = "GET_BLOG_ERROR";

export const CREATE_BLOG_REQUESTING = "CREATE_BLOG_REQUESTING";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";

export const UPDATE_BLOG_REQUESTING = "UPDATE_BLOG_REQUESTING";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_ERROR = "UPDATE_BLOG_ERROR";

export const DELETE_BLOG_REQUESTING = "DELETE_BLOG_REQUESTING";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";