export const FILTER_COURSES_REQUEST = "FILTER_COURSES_REQUEST";
export const FILTER_COURSES_REQUESTING = "FILTER_COURSES_REQUESTING";
export const FILTER_COURSES_SUCCESS = "FILTER_COURSES_SUCCESS";
export const FILTER_COURSES_ERROR = "FILTER_COURSES_ERROR";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_REQUESTING = "CREATE_COURSE_REQUESTING";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_ERROR = "CREATE_COURSE_ERROR";