export const FILTER_QUIZZES_REQUEST = "FILTER_QUIZZES_REQUEST";
export const FILTER_QUIZZES_REQUESTING = "FILTER_QUIZZES_REQUESTING";
export const FILTER_QUIZZES_SUCCESS = "FILTER_QUIZZES_SUCCESS";
export const FILTER_QUIZZES_ERROR = "FILTER_QUIZZES_ERROR";

export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_REQUESTING = "CREATE_QUIZ_REQUESTING";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_ERROR = "CREATE_QUIZ_ERROR";

export const GET_QUIZ_REQUEST = "GET_QUIZ_REQUEST";
export const GET_QUIZ_REQUESTING = "GET_QUIZ_REQUESTING";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
export const GET_QUIZ_ERROR = "GET_QUIZ_ERROR";